# Generated by Django 5.1.3 on 2024-11-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_compra_item_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='data_compra',
            new_name='dataCompra',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='valor_total',
            new_name='valorTotal',
        ),
        migrations.AlterField(
            model_name='item',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.compra'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(max_length=50),
        ),
    ]
